version: "3.7"

services:
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - hemocione_local

  maria_db:
    image: "mariadb:10.5"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: hemocione
      MYSQL_USER: user
      MYSQL_PASSWORD: changeme
    ports:
      - "3306:3306"
    volumes:
      - hemocione_data:/var/lib/mysql
    networks:
      - hemocione_local

  mongo_db:
    image: "mongo:4.4.4"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - hemocione_local

  rails_api:
    build: .
    container_name: hemocione_api
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - maria_db
      - redis
      - mongo_db
      - inbucket
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: hemocione
      MYSQL_USER: root
      MYSQL_PASSWORD: changeme
      MONGO_USERNAME: root
      MONGO_PASSWORD: rootpassword
      DEVISE_JWT_SECRET_KEY: aae75c2b1e5edcd5ccfcd42e0b4049981cded5845bacfe4a74bf843bb18357181664d032e316f8e01e9f2aa5299fdcd4ca76755c014b2e4aed999586bf00bd67
    volumes:
      - "../hemocione-backend:/srv/backend/"
      - "rails_api-usrlocal:/usr/local/"
    tty: true
    stdin_open: true
    networks:
      - hemocione_local

  inbucket:
    image: inbucket/inbucket:stable
    ports:
      - "9000:9000"
      - "2500:2500"
    networks:
      - hemocione_local

volumes:
  hemocione_data:
  rails_api-usrlocal:
  redis-data:
  mongodb_data:

networks:
  hemocione_local: